const pluList = [
	{item: 'aloe',
	plu: 3064},
	{item: 'cortland',
	plu: 4104},
	{item: 'cosmic crisp',
	plu: 3507},
	{item: 'empire',
	plu: 4124},
	{item: 'envy',
	plu: 3616},
	{item: 'fuji',
	plu: 4131},
	{item: 'gala',
	plu: 4132},
	{item: 'granny smith',
	plu: 4017},
	{item: 'honeycrisp',
	plu: 3283},
	{item: 'macoun',
	plu: 3073},
	{item: 'mcintosh',
	plu: 4019},
	{item: 'pazzaz',
	plu: 3445},
	{item: 'pink lady',
	plu: 4119},
	{item: 'red delicious',
	plu: 4016},
	{item: 'sugarbee',
	plu: 3486},
	{item: 'sweetango',
	plu: 3603},
	{item: 'apricot',
	plu: 4218},
	{item: 'artichoke',
	plu: 4084},
	{item: 'asparagus',
	plu: 4080},
	{item: 'avocado',
	plu: 4771},
	{item: 'baby banana',
	plu: 4234},
	{item: 'banana',
	plu: 4011},
	{item: 'batata',
	plu: 4546},
	{item: 'green beans',
	plu: 4066},
	{item: 'beets',
	plu: 4540},
	{item: 'golden beets',
	plu: 3273},
	{item: 'red beets',
	plu: 4538},
	{item: 'bittermelon',
	plu: 4783},
	{item: 'bok choy',
	plu: 4545},
	{item: 'baby bok choy',
	plu: 4544},
	{item: 'broccoli',
	plu: 4060},
	{item: 'broccoli crowns',
	plu: 4549},
	{item: 'broccoli rabe',
	plu: 4547},
	{item: 'brussels sprouts',
	plu: 4550},
	{item: 'brussels sprouts stalk',
	plu: 3083},
	{item: 'green cabbage',
	plu: 4069},
	{item: 'napa cabbage',
	plu: 4552},
	{item: 'red cabbage',
	plu: 4554},
	{item: 'savory cabbage',
	plu: 4555},
	{item: 'carrots',
	plu: 94562},
	{item: 'carrots bunch',
	plu: 94094},
	{item: 'celery',
	plu: 4578},
	{item: 'celery root',
	plu: 4585},
	{item: 'green chard',
	plu: 4586},
	{item: 'red chard',
	plu: 4587},
	{item: 'cilantro',
	plu: 4889},
	{item: 'chives',
	plu: 4888},
	{item: 'coconut',
	plu: 4261},
	{item: 'white coconut',
	plu: 4262},
	{item: 'corn',
	plu: 4078},
	{item: 'cucumber',
	plu: 4062},
	{item: 'daikon radish',
	plu: 4598},
	{item: 'dill',
	plu: 4891},
	{item: 'eggplant',
	plu: 4081},
	{item: 'baby eggplant',
	plu: 4599},
	{item: 'baby white eggplant',
	plu: 4600},
	{item: 'sicilian eggplant',
	plu: 3171},
	{item: 'belgian endive',
	plu: 4543},
	{item: 'curly endive',
	plu: 4604},
	{item: 'escarole',
	plu: 4605},
	{item: 'fennel',
	plu: 4515},
	{item: 'garlic',
	plu: 4608},
	{item: 'ginger',
	plu: 4612},
	{item: 'red grapefruit',
	plu: 4047},
	{item: 'cotton candy grapes',
	plu: 3501},
	{item: 'green seedless grapes',
	plu: 4022},
	{item: 'red seedless grapes',
	plu: 4023},
	{item: 'collard greens',
	plu: 4614},
	{item: 'dandelion greens',
	plu: 4615},
	{item: 'mustard greens',
	plu: 4616},
	{item: 'turnip greens',
	plu: 4619},
	{item: 'jicama',
	plu: 4626},
	{item: 'kale',
	plu: 4627},
	{item: 'kiwi',
	plu: 4030},
	{item: 'kohlrabi',
	plu: 4628},
	{item: 'leeks',
	plu: 4629},
	{item: 'lemongrass',
	plu: 4894},
	{item: 'lemon',
	plu: 4053},
	{item: 'boston lettuce',
	plu: 4632},
	{item: 'green lettuce',
	plu: 4076},
	{item: 'red lettuce',
	plu: 4075},
	{item: 'romaine lettuce',
	plu: 4640},
	{item: 'lime',
	plu: 4048},
	{item: 'malanga',
	plu: 4644},
	{item: 'mandarins',
	plu: 4055},
	{item: 'green mango',
	plu: 4584},
	{item: 'red mango',
	plu: 4584},
	{item: 'yellow mango',
	plu: 4312},
	{item: 'cantaloupe',
	plu: 4347},
	{item: 'honeydew',
	plu: 4034},
	{item: 'watermelon mini seedless',
	plu: 3421},
	{item: 'watermelon red seedless',
	plu: 4032},
	{item: 'mint',
	plu: 4896},
	{item: 'white nectarine',
	plu: 3035},
	{item: 'yellow nectarine',
	plu: 4378},
	{item: 'green onion',
	plu: 4068},
	{item: 'red onion',
	plu: 4082},
	{item: 'yellow onion',
	plu: 4093},
	{item: 'sweet onion',
	plu: 4161},
	{item: 'white onion',
	plu: 4663},
	{item: 'blood orange',
	plu: 4381},
	{item: 'navel orange',
	plu: 4385},
	{item: 'oregano',
	plu: 4897},
	{item: 'papaya',
	plu: 4394},
	{item: 'curly parsley',
	plu: 4899},
	{item: 'italian parsley',
	plu: 4901},
	{item: 'parsnip',
	plu: 4672},
	{item: 'passionfruit',
	plu: 4397},
	{item: 'white peach',
	plu: 4400},
	{item: 'yellow peach',
	plu: 3116},
	{item: 'asian pear',
	plu: 4408},
	{item: 'bartlett pear',
	plu: 4409},
	{item: 'bosc pear',
	plu: 4411},
	{item: 'danjou pear',
	plu: 4416},
	{item: 'red bartlett pear',
	plu: 4410},
	{item: 'snow peas',
	plu: 4092},
	{item: 'sugar snap peas',
	plu: 4675},
	{item: 'pepino',
	plu: 4333},
	{item: 'anaheim pepper',
	plu: 4677},
	{item: 'fresno pepper',
	plu: 4712},
	{item: 'green bell pepper',
	plu: 4065},
	{item: 'hungarian wax pepper',
	plu: 4690},
	{item: 'italian sweet pepper',
	plu: 4687},
	{item:'jalepeno pepper',
	plu: 4693},
	{item: 'long green hot pepper',
	plu: 4696},
	{item: 'orange bell pepper',
	plu: 4682},
	{item: 'poblano pepper',
	plu: 4705},
	{item: 'red bell pepper',
	plu: 4088},
	{item: 'red hot cherry pepper',
	plu: 4691},
	{item: 'serrano pepper',
	plu: 4709},
	{item: 'yellow bell pepper',
	plu: 4680},
	{item: 'persimmon',
	plu: 4428},
	{item: 'pineapple',
	plu: 4430},
	{item: 'plantain',
	plu: 4235},
	{item: 'pomegrante',
	plu: 4445},
	{item: 'russet potato',
	plu: 4072},
	{item: 'red potato',
	plu: 4073},
	{item: 'yellow potato',
	plu: 4727},
	{item: 'quince',
	plu: 4447},
	{item: 'radicchio',
	plu: 4738},
	{item: 'black radish',
	plu: 4739},
	{item: 'radish',
	plu: 94089},
	{item: 'watermelon radish',
	plu: 4744},
	{item: 'rutabaga',
	plu: 4747},
	{item: 'sage',
	plu: 4904},
	{item: 'shallot',
	plu: 4662},
	{item: 'acorn squash',
	plu: 4750},
	{item: 'butternut squash',
	plu: 4759},
	{item: 'chayote squash',
	plu: 4761},
	{item:'opo squash',
	plu: 3141},
	{item: 'spaghetti squash',
	plu: 4776},
	{item: 'yellow squash',
	plu: 4086},
	{item: 'zucchini squash',
	plu: 4067},
	{item: 'sunchoke',
	plu: 4791},
	{item: 'sweet potato',
	plu: 4074},
	{item: 'japanese sweet potato',
	plu: 4816},
	{item: 'orange sweet potato',
	plu: 4817},
	{item: 'taro',
	plu: 4794},
	{item: 'tarragon',
	plu: 4906},
	{item: 'thyme',
	plu: 4907},
	{item: 'tomatillos',
	plu: 4801},
	{item: 'vine tomato',
	plu: 4664},
	{item: 'roma tomato',
	plu: 4087},
	{item: 'turnip',
	plu: 4811},
	{item: 'turmeric',
	plu: 4918},
	{item: 'yuca',
	plu: 4819},
	];

const answerDisplay = document.getElementById('answerDisplay');

const one = document.getElementById('digitButton1');
const two = document.getElementById('digitButton2');
const three = document.getElementById('digitButton3');
const four = document.getElementById('digitButton4');
const five = document.getElementById('digitButton5');
const six = document.getElementById('digitButton6');
const seven = document.getElementById('digitButton7');
const eight = document.getElementById('digitButton8');
const nine = document.getElementById('digitButton9');
const zero = document.getElementById('digitButton0');

const plus = document.getElementById('digitButtonPlus');
const minus = document.getElementById('digitButtonMinus');
const multi = document.getElementById('digitButtonMulti');
const divise = document.getElementById('digitButtonDivise');

const clear = document.getElementById('digitButtonClear');
const go = document.getElementById('digitButtonGo');

const searchBox = document.getElementById("searchBox");
const searchBoxButton = document.getElementById("searchBoxButton");

const digitContainer = document.getElementById("digitButtonContainer")

digitContainer.addEventListener('click', function(e) {
	if (e.target.nodeName === "BUTTON" && e.target.id === "digitButtonClear") {
		answerDisplay.innerHTML = "";
	}

	else if (e.target.nodeName === "BUTTON" && e.target.id === "digitButtonGo") {
  		let answer = eval(answerDisplay.innerHTML);
  		answerDisplay.innerHTML = answer;
  		return
  }


  else if (e.target.nodeName === "BUTTON") {
  		answerDisplay.innerHTML = answerDisplay.innerHTML + e.target.innerHTML
  }

  console.log(e.target);
});

searchBoxButton.addEventListener('click', function(e) {
	let itemInQuestion = searchBox.value;
	for (i=0; i < pluList.length; i++) {
		if (pluList[i].item === itemInQuestion) {
			answerDisplay.innerHTML = pluList[i].plu;
		}
	}
})


